import React, { useState } from "react";
import { FaChevronCircleDown } from "react-icons/fa";
import OptionsTop from "../../components/OptionsTop";
import "../Platform.css";

// Dados dos vídeos com título
const VideoData = [
  {
    id: 1,
    title: "Episode 1 - Introduction", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/CPIw6I--s2Y",
    words: [
      { id: "word1", correctAnswer: "name" },
      { id: "word2", correctAnswer: "months" },
      { id: "word3", correctAnswer: "visited" },
      { id: "word4", correctAnswer: "meetings" },
      { id: "word5", correctAnswer: "writers" },
      { id: "word6", correctAnswer: "sightseeing" },
      { id: "word7", correctAnswer: "punctual" },
      { id: "word8", correctAnswer: "coming" },
    ],
    videoDescription: [
      "My ",
      { word: "word1" },
      "is Jenny Zelinski. I live and work in New York. I'm the assistent editor of a magazine called NewYork24Seven. A few ",
      { word: "word2" },
      " ago, I ",
      { word: "word3" },
      "our office in London to learn more about the company. I met the manager, Daniel O'Conner. I had lots of",
      { word: "word4" },
      "with him, of course. And a working dinner on my birthday. But I spent more time with Rob Walker. He's one of the",
      { word: "word5" },
      "on the London magazine. We had coffees together. We went",
      { word: "word6" },
      ". I even helped Rob buy a t-shirt! He was fun to be with. I liked him a lot. I think he liked me, too. Rob isn't the most",
      { word: "word7" },
      "person in the world, but he's a great writer. We invited him to work for the New York magazine for a month, and he agreed. So now Rob's",
      { word: "word8" },
      "to New York. I know he's really excited about it. It's going to be great to see him again.",

      ".",
    ],
  },
  {
    id: 2,
    title: "Episode 1 - Calling Reception", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/4DAYuqnf5NA",
    words: [
      { id: "word1", correctAnswer: "613" },
      { id: "word2", correctAnswer: "help" },
      { id: "word3", correctAnswer: "There's" },
      { id: "word4", correctAnswer: "air-conditioning" },
      { id: "word5", correctAnswer: "working" },
      { id: "word6", correctAnswer: "room" },
      { id: "word7", correctAnswer: "send" },
      { id: "word8", correctAnswer: "right" },
      { id: "word9", correctAnswer: "evening" },
      { id: "word10", correctAnswer: "bother" },
      { id: "word11", correctAnswer: "613" },
      { id: "word12", correctAnswer: "help" },
      { id: "word13", correctAnswer: "can't" },
      { id: "word14", correctAnswer: "put" },
    ],
    videoDescription: [
      "Hello, reception. Hello, this is room",
      { word: "word1" },
      "How can I",
      { word: "word2" },
      "you?",
      { word: "word3" },
      "a problem with the",
      { word: "word4" },
      "It isn't",
      { word: "word5" },
      "and it's very hot in my",
      { word: "word6" },
      "I'm sorry, sir. I'll",
      { word: "word7" },
      "somebody to look at it",
      { word: "word8" },
      "now. Thank you. Good",
      { word: "word9" },
      "reception. Hello, Im sorry to",
      { word: "word10" },
      "you again. This is room",
      { word: "word11" },
      "How can I",
      { word: "word12" },
      "you? I have a problem with the Wi-Fi. I",
      { word: "word13" },
      "get a signal. I'm sorry, sir. I'll",
      { word: "word14" },
      "you through to IT. Thanks.",
    ],
  },
  {
    id: 3,
    title: "Episode 1 - Jenny and Rob me again", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/OGTPrCK3HS0",
    words: [
      { id: "word1", correctAnswer: "great" },
      { id: "word2", correctAnswer: "really" },
      { id: "word3", correctAnswer: "exciting" },
      { id: "word4", correctAnswer: "view" },
      { id: "word5", correctAnswer: "buildings" },
      { id: "word6", correctAnswer: "introduce" },
      { id: "word7", correctAnswer: "boss" },
      { id: "word8", correctAnswer: "start" },
      { id: "word9", correctAnswer: "ideas" },
      { id: "word10", correctAnswer: "tired" },
      { id: "word11", correctAnswer: "That's" },
      { id: "word12", correctAnswer: "finish" },
      { id: "word13", correctAnswer: "guess" },
      { id: "word14", correctAnswer: "that" },
      { id: "word15", correctAnswer: "just" },
      { id: "word16", correctAnswer: "way" },
      { id: "word17", correctAnswer: "again" },
    ],
    videoDescription: [
      "So, here you are in New York at last. Yeah, it's",
      { word: "word1" },
      "to be here. It's",
      { word: "word2" },
      "",
      { word: "word3" },
      "And how's your hotel? It's fine. My room is really nice. Do you have a good",
      { word: "word4" },
      "from your room? I can see lots of",
      { word: "word5" },
      "Tomorrow I'm going to show you around the office and",
      { word: "word6" },
      "you to the team. Barbara's looking forward to meeting you. You remember Barbara, my",
      { word: "word7" },
      "? Oh, yeah, sorry. And then you can",
      { word: "word8" },
      "thinking about your blog and the column. Have you got any",
      { word: "word9" },
      "yet, Rob? Rob? What? Sorry, Jenny. You must be really",
      { word: "word10" },
      " Yes, I am a bit. What time is it now? It's nine o'clock. Nine o'clock?",
      { word: "word11" },
      "two o'clock in the morning for me. Let's",
      { word: "word12" },
      "our drinks. You need to go to bed. I",
      { word: "word13" },
      "you're right. So, I'll see you in the office at eleven in the morning. At eleven? Is",
      { word: "word14" },
      "OK? It's perfect. Thanks, Jenny. There's",
      { word: "word15" },
      "one thing. What's that? Don't be late. By the",
      { word: "word16" },
      "it's great to see you",
      { word: "word17" },
      "Yeah. It's great to see you, too.",
    ],
  },
  {
    id: 4,
    title: "Episode 2 - In the New York Office", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/Cb3_XHGm1iw",
    words: [
      { id: "word1", correctAnswer: "everything" },
      { id: "word2", correctAnswer: "brilliant" },
      { id: "word3", correctAnswer: "bigger" },
      { id: "word4", correctAnswer: "finally" },
      { id: "word5", correctAnswer: "came" },
      { id: "word6", correctAnswer: "hope" },
      { id: "word7", correctAnswer: "unfortunately" },
      { id: "word8", correctAnswer: "We're" },
      { id: "word9", correctAnswer: "working" },
      { id: "word10", correctAnswer: "photographer" },
      { id: "word11", correctAnswer: "earlier" },
    ],
    videoDescription: [
      "Well, I think that's",
      { word: "word1" },
      ". What do you think of the office? It's",
      { word: "word2" },
      "and much",
      { word: "word3" },
      "than our place in London. Oh, here's Barbara. Rob, this is Barbara, the editor of the magazine. It's good to",
      { word: "word4" },
      "meet you Rob. It's great to be here. Is this your first time in New York? No, I",
      { word: "word5" },
      "here when I was 18. But only for a few days. Well, I",
      { word: "word6" },
      "you get to know New York much better this time. Barbara I'm going to take Rob out for lunch. Would you like to come with us? I'd love to but",
      { word: "word7" },
      " I have a meeting at one. So I'll see you later. We're meeting at 3. I think that's right. Have a nice lunch. Hey, are you Rob Walker? Yes. Hi, I'm Holly Holly Tyler. Hello, Holly. ",
      { word: "word8" },
      "going to be",
      { word: "word9" },
      "together. Really? Didn't Barbara tell you I'm going to be Rob's",
      { word: "word10" },
      "? Oh Well, we're just going for lunch. Cool. I can come with you. I mean I had a sandwich",
      { word: "word11" },
      "so I don't need to eat. But Rob and I can talk. Is that okay? Sure. So let’s go.",
    ],
  },
  {
    id: 5,
    title: "Episode 2 - At the restaurant", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/8QPSKBi1m8Q",
    words: [
      { id: "word1", correctAnswer: "order" },
      { id: "word2", correctAnswer: "start" },
      { id: "word3", correctAnswer: "like" },
      { id: "word4", correctAnswer: "green" },
      { id: "word5", correctAnswer: "have" },
      { id: "word6", correctAnswer: "baked" },
      { id: "word7", correctAnswer: "How" },
      { id: "word8", correctAnswer: "well" },
      { id: "word9", correctAnswer: "water" },
      { id: "word10", correctAnswer: "for" },
      { id: "word11", correctAnswer: "asked" },
      { id: "word12", correctAnswer: "change" },
      { id: "word13", correctAnswer: "done" },
      { id: "word14", correctAnswer: "kitchen" },
    ],
    videoDescription: [
      "Are you ready to",
      { word: "word1" },
      "? Yes, please. Can I get you something to ",
      { word: "word2" },
      "with? No, thank you. I'd ",
      { word: "word3" },
      "the tuna with a ",
      { word: "word4" },
      "salad. And for you, sir? I'll ",
      { word: "word5" },
      "the steak, please. Would you like that with fries or a",
      { word: "word6" },
      "potate? Fries, please. ",
      { word: "word7" },
      "would you like your steak? Rare, medium or ",
      { word: "word8" },
      "done? Well done. Nothing for me. Ok. And to drink?",
      { word: "word9" },
      ", please. Still or sparkling? Sparkling. The tuna",
      { word: "word10" },
      "you, ma'am, and the steak for you, sir. I'm sorry, but I ",
      { word: "word11" },
      "for a green salad, not fries. No problem, I'll ",
      { word: "word12" },
      "it. Excuse me. Yes, sir? Sorry, I asked for my steak well ",
      { word: "word13" },
      "and this is rare. I'm really sorry. I'll take it back to the ",
      { word: "word14" },
      ".",
    ],
  },
  {
    id: 6,
    title: "Episode 2 - Holly and Rob make friends", // Título do vídeo
    videoSrc: "https://youtube.com/embed/aBbOcnqeDFg",
    words: [
      { id: "word1", correctAnswer: "write" },
      { id: "word2", correctAnswer: "impressions" },
      { id: "word3", correctAnswer: "nightlife" },
      { id: "word4", correctAnswer: "planning" },
      { id: "word5", correctAnswer: "suggestions" },
      { id: "word6", correctAnswer: "know" },
      { id: "word7", correctAnswer: "theater" },
      { id: "word8", correctAnswer: "could" },
      { id: "word9", correctAnswer: "actors" },
      { id: "word10", correctAnswer: "bring" },
      { id: "word11", correctAnswer: "have" },
      { id: "word12", correctAnswer: "think" },
      { id: "word13", correctAnswer: "bottles" },
      { id: "word14", correctAnswer: "really" },
      { id: "word15", correctAnswer: "get" },
      { id: "word16", correctAnswer: "have" },
      { id: "word17", correctAnswer: "fantastic" },
      { id: "word18", correctAnswer: "three" },
    ],
    videoDescription: [
      "So tell me, Rob. What are you going to ",
      { word: "word1" },
      "about? Well, to start with, my first ",
      { word: "word2" },
      "of New York. You know, the ",
      { word: "word3" },
      ", the music, things like that. Are you ",
      { word: "word4" },
      "to do any interviews? I'd like to. Do you have any ",
      { word: "word5" },
      "? Well, I know some great musicians. Musicians? You",
      { word: "word6" },
      ", guys in a band. And I also have some contacts in the",
      { word: "word7" },
      "and dance. That would be great. Maybe we",
      { word: "word8" },
      "go to a show, and after you could talk to the",
      { word: "word9" },
      ". I really like that idea. Can I ",
      { word: "word10" },
      "you anything else? Could we ",
      { word: "word11" },
      "the check, please? Yes, ma'am. Here's your check. Thanks. Excuse me. I ",
      { word: "word12" },
      "there's a mistake. We had two",
      { word: "word13" },
      "of water, not three. You're right. I'm ",
      { word: "word14" },
      "sorry. It's not my day today. I'll ",
      { word: "word15" },
      "you a new check. Thank you.We're going to ",
      { word: "word16" },
      "a fun month, Rob. Yes. I think it's going to be ",
      { word: "word17" },
      ". OK. Time to go. You have your meeting with Barbara at ",
      { word: "word18" },
      ".Oh, yeah. Right.",
    ],
  },
  {
    id: 7,
    title: "Episode 3 - Rob has a problem", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/CPIw6I--s2Y",
    words: [
      { id: "word1", correctAnswer: "bit" },
      { id: "word2", correctAnswer: "exactly" },
      { id: "word3", correctAnswer: "eating" },
      { id: "word4", correctAnswer: "out" },
      { id: "word5", correctAnswer: "exercise" },
      { id: "word6", correctAnswer: "enough" },
      { id: "word7", correctAnswer: "cycle" },
      { id: "word8", correctAnswer: "here" },
      { id: "word9", correctAnswer: "anyway" },
      { id: "word10", correctAnswer: "goes" },
      { id: "word11", correctAnswer: "boring" },
      { id: "word12", correctAnswer: "keen" },
      { id: "word13", correctAnswer: "basketball" },
      { id: "word14", correctAnswer: "don't" },
      { id: "word15", correctAnswer: "buy" },
      { id: "word16", correctAnswer: "across" },
    ],
    videoDescription: [
      "Hey, Rob. Come on. Keep up. Sorry. I'm a ",
      { word: "word1" },
      "tired this morning. You aren't ",
      { word: "word2" },
      "in good shape, are you? I know, I know. I think I'm ",
      { word: "word3" },
      "too much. Then eat less. It isn't easy. I eat",
      { word: "word4" },
      "all the time. And the portions in American restaurants are enormous. You don't do enough",
      { word: "word5" },
      ". I walk a lot. Walking isn't ",
      { word: "word6" },
      ", Rob. Do you do anything to keep fit? I ",
      { word: "word7" },
      "when I'm in London. So why don't you get a bike ",
      { word: "word8" },
      "? I'm only here for another three weeks.",
      { word: "word9" },
      ", my hotel's near the office. I don't need a bike. You know. Jennifer",
      { word: "word10" },
      "unning all the time. Before and after work. But I just think that running is just so",
      { word: "word11" },
      ". I mean, where's the fun? Yeah, I'm not very ",
      { word: "word12" },
      "on running. So why don't play ",
      { word: "word13" },
      "with me and my friends? OK. That's a great idea. But I",
      { word: "word14" },
      "have any trainers. Trainers? Sneakers. You can",
      { word: "word15" },
      "some. Is there a sports shop near here? Sure. There's one ",
      { word: "word16" },
      "the street",
    ],
  },
  {
    id: 8,
    title: "Episode 3 - Take Something back to a store", // Título do vídeo
    videoSrc: "https://youtube.com/embed/cRrW_8kLKJY",
    words: [
      { id: "word1", correctAnswer: "these" },
      { id: "word2", correctAnswer: "These" },
      { id: "word3", correctAnswer: "them" },
      { id: "word4", correctAnswer: "much" },
      { id: "word5", correctAnswer: "sales" },
      { id: "word6", correctAnswer: "bought" },
      { id: "word7", correctAnswer: "remember" },
      { id: "word8", correctAnswer: "afraid" },
      { id: "word9", correctAnswer: "pair" },
      { id: "word10", correctAnswer: "don't" },
      { id: "word11", correctAnswer: "same" },
      { id: "word12", correctAnswer: "refund" },
      { id: "word13", correctAnswer: "receipt" },
    ],
    videoDescription: [
      "Can I help you, sir? Yes. Do you have ",
      { word: "word1" },
      "in an eight? Just a minute. I'll go and check. Here you are.",
      { word: "word2" },
      "are an eight. Do you want to try ",
      { word: "word3" },
      "on? No, thanks. I'm sure they'll be fine. How ",
      { word: "word4" },
      "are they? They're $83,94. Oh, it says $72,99. Yes, but there's an added ",
      { word: "word5" },
      "tax of 15%. Oh, OK. Do you take Mastercard? Sure. Can I help you? Yes. I ",
      { word: "word6" },
      "these about half an hour ago. Yes, I",
      { word: "word7" },
      ". Is there a problem? Yes. I'm",
      { word: "word8" },
      "they're too small. What size are they? They're an eight. But I take a UK eight. Oh, right. Yes, a UK eight is a US nine. Do you have a",
      { word: "word9" },
      "? I'll go and check. Just a minute. I'm sorry, but we ",
      { word: "word10" },
      "have these in a nine. But we have these and they're the",
      { word: "word11" },
      "price. Or you can have a ",
      { word: "word12" },
      ". Uh, I'll take this pair then, please. No problem. Do you have the",
      { word: "word13" },
      "? Yes, here you are. Brilliant.",
    ],
  },
  {
    id: 9,
    title: "Episode 3 - Rob Decides to Exercise", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/JgWZ5z8kcWE",
    words: [
      { id: "word1", correctAnswer: "had" },
      { id: "word2", correctAnswer: "went" },
      { id: "word3", correctAnswer: "interesting" },
      { id: "word4", correctAnswer: "bought" },
      { id: "word5", correctAnswer: "did" },
      { id: "word6", correctAnswer: "impressed" },
      { id: "word7", correctAnswer: "beautiful" },
      { id: "word8", correctAnswer: "come" },
      { id: "word9", correctAnswer: "time" },
      { id: "word10", correctAnswer: "later" },
      { id: "word11", correctAnswer: "fifteen" },
      { id: "word12", correctAnswer: "running" },
    ],
    videoDescription: [
      "Hi, Jenny. Oh, hi. Have you ",
      { word: "word1" },
      "a good day? Oh, you know. Meetings. What about you? It was great. I ",
      { word: "word2" },
      "to Brooklyn and met some really",
      { word: "word3" },
      "people. And you had time to go shopping, too. What? Oh, yeah. I've just",
      { word: "word4" },
      "these. What are they? A pair of trainers. Uh, sneakers. Nice. Why",
      { word: "word5" },
      "you buy sneakers? I think I need to get a bit fitter. Oh, I'm",
      { word: "word6" },
      ". You know, I go running every morning in Central Park. Do you? It's so",
      { word: "word7" },
      "early in the morning. Why don't you",
      { word: "word8" },
      "with me? Uh, sure. Why not? Great. I'll come by your hotel tomorrow morning. Oh. What ",
      { word: "word9" },
      "? Six forty-five? Six? Forty-five. Six? Forty-five. Can we make a bit ",
      { word: "word10" },
      ". Say, seven forty-five? That's too late, Rob. Let's make it seven",
      { word: "word11" },
      "OK. Excellent. See you later. Great. Basketball and",
      { word: "word12" },
      ", Rob. You must have a lot of energy. Uh, yeah.",
    ],
  },
  {
    id: 10,
    title: "Episode 4 - Running in Central Park", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/tTebIejXrAA",
    words: [
      { id: "word1", correctAnswer: "isn't" },
      { id: "word2", correctAnswer: "all" },
      { id: "word3", correctAnswer: "came" },
      { id: "word4", correctAnswer: "course" },
      { id: "word5", correctAnswer: "saying" },
      { id: "word6", correctAnswer: "shape" },
      { id: "word7", correctAnswer: "out" },
      { id: "word8", correctAnswer: "place" },
      { id: "word9", correctAnswer: "healthier" },
      { id: "word10", correctAnswer: "anything" },
      { id: "word11", correctAnswer: "Absolutely" },
    ],
    videoDescription: [
      "Are you OK? Me? Never better. It's beautiful here,",
      { word: "word1" },
      "? I think this is my favorite place in New York. Yeah. It's great. So how's it",
      { word: "word2" },
      "going? Are you happy you",
      { word: "word3" },
      "? To Central Park? At seven fifteen in the morning? To New York, Rob. Yeah. Of",
      { word: "word4" },
      ". I'm happy. It's fantastic. Really? You aren't just",
      { word: "word5" },
      "that. No, I mean it. You need to get in",
      { word: "word6" },
      ", Rob. I know. I am a bit tired of eating",
      { word: "word7" },
      "all the time. It isn't good for my figure. It's the restaurants you go to? Why don't you come over to my",
      { word: "word8" },
      "after work? I could make you something a little",
      { word: "word9" },
      ". I'd really like that. Thanks. So, how do you feel now? Are you ready to go again? Oh yes. I'm ready for",
      { word: "word10" },
      ". Are you sure you're OK? ",
      { word: "word11" },
      "OK. We'll only go around two more times. Two? Excellent.",
    ],
  },
  {
    id: 11,
    title: "Episode 4 - Going to a pharmacy", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/QebfSsp7t3k",
    words: [
      { id: "word1", correctAnswer: "feeling" },
      { id: "word2", correctAnswer: "headache" },
      { id: "word3", correctAnswer: "cough" },
      { id: "word4", correctAnswer: "temperature" },
      { id: "word5", correctAnswer: "allergic" },
      { id: "word6", correctAnswer: "many" },
      { id: "word7", correctAnswer: "often" },
      { id: "word8", correctAnswer: "forty" },
      { id: "word9", correctAnswer: "eight" },
      { id: "word10", correctAnswer: "much" },
    ],
    videoDescription: [
      "Good morning. Can I help you? I'm not",
      { word: "word1" },
      "very well. I think I have flu. What are your symptoms? I have a",
      { word: "word2" },
      "and a",
      { word: "word3" },
      ". Do you have a",
      { word: "word4" },
      "? No, I don't think so. Are you",
      { word: "word5" },
      "to any drugs? I'm allergic to penicillin. No problem. This is ibuprofen. It'll make you feel better. How",
      { word: "word6" },
      "do I have to take? Two every four hours. Sorry? How",
      { word: "word7" },
      "? Two every four hours. If you don't feel better in",
      { word: "word8" },
      "",
      { word: "word9" },
      "hours, you should see a doctor. OK, thanks. How",
      { word: "word10" },
      "is that? That's $6,99, please. Thank you. You're welcome.",
    ],
  },
  {
    id: 12,
    title: "Episode 4 - Dinner at Jenny's Apartment", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/6h394NiP8Ss",
    words: [
      { id: "word1", correctAnswer: "meal" },
      { id: "word2", correctAnswer: "offer" },
      { id: "word3", correctAnswer: "looking" },
      { id: "word4", correctAnswer: "broke" },
      { id: "word5", correctAnswer: "met" },
      { id: "word6", correctAnswer: "recently" },
      { id: "word7", correctAnswer: "guess" },
      { id: "word8", correctAnswer: "energy" },
      { id: "word9", correctAnswer: "mean" },
      { id: "word10", correctAnswer: "weren't" },
      { id: "word11", correctAnswer: "wanted" },
      { id: "word12", correctAnswer: "glad" },
      { id: "word13", correctAnswer: "another" },
      { id: "word14", correctAnswer: "busy" },
      { id: "word15", correctAnswer: "much" },
      { id: "word16", correctAnswer: "street" },
      { id: "word17", correctAnswer: "I'll" },
      { id: "word18", correctAnswer: "" },
    ],
    videoDescription: [
      "That was a lovely ",
      { word: "word1" },
      ". Thanks, Jenny. That's OK. It's been great being in New York. You know, your",
      { word: "word2" },
      "to work here came at a very good time for me. Really ?  Yeah. I was",
      { word: "word3" },
      "for something new. Something different. You see, I",
      { word: "word4" },
      "up with my girlfriend a few months before I",
      { word: "word5" },
      "you. Oh, right. What about you? What about me? You know, relationships ? Oh, I've been to busy ",
      { word: "word6" },
      "to think about relationships. Getting this job at the magazine was a really big thing for me. I ",
      { word: "word7" },
      "that's taken up all my time and ",
      { word: "word8" },
      ". But that isn't very good for you. Only thinking about working, I ",
      { word: "word9" },
      ". Why didn't you tell me you ",
      { word: "word10" },
      "feeling well this morning? We didn't have to go for a run. I ",
      { word: "word11" },
      "to go. It was nice. Well, I'm",
      { word: "word12" },
      "you're feeling better. Would you like ",
      { word: "word13" },
      "coffee? No, thanks. I think I should get back to the hotel now. I've got a really",
      { word: "word14" },
      "day tomorrow. Do you have a telephone number for a taxi? Yeah, but It's",
      { word: "word15" },
      "better to get a cab on the",
      { word: "word16" },
      ". Oh, OK, then. I'll see you in the morning, if you're feeling OK. Oh, I'm sure",
      { word: "word17" },
      "be fine. Thanks again for a great evening. Any time. Good night. Night, Rob.",
    ],
  },
  {
    id: 13,
    title: "Episode 5 - Holly and Rob in Brooklyn", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/fvMX9BOmpDI",
    words: [
      { id: "word1", correctAnswer: "interview" },
      { id: "word2", correctAnswer: "They're" },
      { id: "word3", correctAnswer: "another" },
      { id: "word4", correctAnswer: "anybody" },
      { id: "word5", correctAnswer: "restroom" },
      { id: "word6", correctAnswer: "there" },
      { id: "word7", correctAnswer: "still" },
      { id: "word8", correctAnswer: "worry" },
      { id: "word9", correctAnswer: "subway" },
    ],
    videoDescription: [
      "That was a good day's work, Rob. You did a great",
      { word: "word1" },
      ". You took some great photos, too.",
      { word: "word2" },
      "really nice. Thanks. Hey, let's have",
      { word: "word3" },
      "coffee. I don't know. I have to get to Manhattan. You don't have to go right now. I'm not sure. I don't want to be late. Why do you have to go to Manhattan? I've got a... A date? You have a date? Mm-hmm. Is it with",
      { word: "word4" },
      "I know? No, it isn't. Anyway, excuse me a minute. I need to go to the",
      { word: "word5" },
      ". That's very American. I'll order more coffees. Okay. Rob? Is that you, Jennifer? Oh. Hi, Holly. Is Rob",
      { word: "word6" },
      "? Yeah. One second. Rob? Not anybody I know, huh? Hi, Jenny. Rob, are you ",
      { word: "word7" },
      "in Brooklyn? Yeah. You know the reservation at the restaurant's for eight, right? Don't",
      { word: "word8" },
      ". I'll be there. Oh, how do I get to Greenwich Village on the",
      { word: "word9" },
      "?",
    ],
  },
  {
    id: 14,
    title: "Episode 5 - Asking how to get there ", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/3mFV66kIJ9g",
    words: [
      { id: "word1", correctAnswer: "station" },
      { id: "word2", correctAnswer: "stops" },
      { id: "word3", correctAnswer: "then" },
      { id: "word4", correctAnswer: "off" },
      { id: "word5", correctAnswer: "could" },
      { id: "word6", correctAnswer: "train" },
      { id: "word7", correctAnswer: "only" },
      { id: "word8", correctAnswer: "straight" },
      { id: "word9", correctAnswer: "called" },
      { id: "word10", correctAnswer: "get" },
    ],
    videoDescription: [
      "How do I get to Greenwich Village on the subway? Go to the subway",
      { word: "word1" },
      "at Prospect Park. Take the B train to West 4th Street. How many",
      { word: "word2" },
      "is that? Six or seven. Okay, and",
      { word: "word3" },
      "? From West 4th Street take the A train and get",
      { word: "word4" },
      "at 14th Street.",
      { word: "word5" },
      "you say that again? Okay. From Prospect Park take the B",
      { word: "word6" },
      "to West 4th Street and then take the A train to 14th Street. That's ",
      { word: "word7" },
      "one stop. Where's the restaurant? Come out of the subway on 8th Avenue. Go ",
      { word: "word8" },
      "on for about 50 yards and take the first left. That's Greenwich Avenue. The restaurant's on the right. It's ",
      { word: "word9" },
      "the Tea Set. Okay, thanks. See you later and don't ",
      { word: "word10" },
      "lost.",
    ],
  },
  {
    id: 15,
    title: "Episode 5 - Rob is late again", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/3mFV66kIJ9g",
    words: [
      { id: "word1", correctAnswer: "underground" },
      { id: "word2", correctAnswer: "stopped" },
      { id: "word3", correctAnswer: "tried" },
      { id: "word4", correctAnswer: "ran" },
      { id: "word5", correctAnswer: "funny" },
      { id: "word6", correctAnswer: "inside" },
      { id: "word7", correctAnswer: "stay" },
      { id: "word8", correctAnswer: "find" },
      { id: "word9", correctAnswer: "young" },
      { id: "word10", correctAnswer: "care" },
      { id: "word11", correctAnswer: "said" },
      { id: "word12", correctAnswer: "point" },
      { id: "word13", correctAnswer: "interested" },
    ],
    videoDescription: [
      "Jenny. I'm here. Hi. I'm so sorry. There was a problem on the ",
      { word: "word1" },
      "We call it the subway here, right? Anyway, the train",
      { word: "word2" },
      "for about 20 minutes. I",
      { word: "word3" },
      "to call but there was no signal. I've been here since seven forty five. I know I",
      { word: "word4" },
      "from the underground Subway station. I'm so sorry. You're always late. It's",
      { word: "word5" },
      ", isn't it? I said, I'm sorry. Look, why don't we go back",
      { word: "word6" },
      "the restaurant? I waited for an hour for you. I don't want to",
      { word: "word7" },
      "here anymore. Maybe we could. We could go for a walk. We could",
      { word: "word8" },
      "another restaurant. I don't feel like I walk. It's been a long day. Okay, but the night is still",
      { word: "word9" },
      ". Maybe you have time to meet up with Holly again. Holly. I'm sorry. I didn't mean to say that. I don't",
      { word: "word10" },
      "about Holly. Forget it Rob. Now if you don't mind, I'd like to go home. Listen to me. Jenny Holly is just a colleague. I ",
      { word: "word11" },
      "forget it. It's okay. No, it isn't okay. Look, I know I'm always late and I know the underground is the subway, but that's not the ",
      { word: "word12" },
      ". I'm not interested in Holly. I came to New York because of you. The only person I'm",
      { word: "word13" },
      "in is you.",
    ],
  },
  {
    id: 16,
    title: "Episode 6 - Rob and Jenny talk about the future", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/y31mzMxsUc0",
    words: [
      { id: "word1", correctAnswer: "believe" },
      { id: "word2", correctAnswer: "nearly" },
      { id: "word3", correctAnswer: "special" },
      { id: "word4", correctAnswer: "same" },
      { id: "word5", correctAnswer: "touch" },
      { id: "word6", correctAnswer: "won't" },
      { id: "word7", correctAnswer: "this" },
      { id: "word8", correctAnswer: "together" },
      { id: "word9", correctAnswer: "somewhere" },
      { id: "word10", correctAnswer: "late" },
      { id: "word11", correctAnswer: "missed" },
      { id: "word12", correctAnswer: "give" },
    ],
    videoDescription: [
      "I can't",
      { word: "word1" },
      "it. Your month here is",
      { word: "word2" },
      "over. It's gone so fast. I know. I've had a great time, Jenny. Me too. It's been really",
      { word: "word3" },
      ". But... But what? Well, it won't be the",
      { word: "word4" },
      "when you're in London and I'm here. But we'll still be in",
      { word: "word5" },
      ". You can visit me in London and I can come back here to see you. It still",
      { word: "word6" },
      "be the same. No. No, it won't. Maybe I could come back to London with you. You can't do that, Jenny. You just got ",
      { word: "word7" },
      "job. That's true. Well, we still have some time",
      { word: "word8" },
      ". We're going out for dinner tonight. Yes. And I'm going to take you",
      { word: "word9" },
      "really nice. Look at the time. I have to go now. It's my lastvinterview in New York. I don't want to be",
      { word: "word10" },
      ". Okay. See you later, then. Bye. Jenny, is Rob here? Oh, you just",
      { word: "word11" },
      "him, Barbara. I really need to talk to him. I'll try him on his cell phone. Hello, Rob. It's Barbara. Can you",
      { word: "word12" },
      "me a call? There's something I'd like to talk about",
    ],
  },
  {
    id: 17,
    title: "Episode 6 - On the phone", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/aVoYRsT3qxk",
    words: [
      { id: "word1", correctAnswer: "wrong" },
      { id: "word2", correctAnswer: "speak" },
      { id: "word3", correctAnswer: "through" },
      { id: "word4", correctAnswer: "desk" },
      { id: "word5", correctAnswer: "leave" },
      { id: "word6", correctAnswer: "try" },
      { id: "word7", correctAnswer: "returning" },
      { id: "word8", correctAnswer: "hold" },
      { id: "word9", correctAnswer: "earlier" },
    ],
    videoDescription: [
      "Hello, Broadway Grill. Oh, sorry, I have the",
      { word: "word1" },
      "number. NewYork24Seven, how can I help you? Hello, can I",
      { word: "word2" },
      "to Barbara Keaton please? Just a second, I'll put you",
      { word: "word3" },
      ". Hello? Hi, is that Barbara? No, I'm sorry. She's not at a",
      { word: "word4" },
      "right now. Can I",
      { word: "word5" },
      "a message please? Sure. Can you tell her Rob Walker called? I'll call back later. I'll give her the message. You could",
      { word: "word6" },
      "her cell phone. Yes, I'll do that. Thank you. I'm sorry, I can't take your call at the moment. Please leave a message after the beep. Hello, Barbara. This is Rob,",
      { word: "word7" },
      "your call. New York24Seven, how can I help you? Hello, it's Rob again. Can I speak to Barbara please? Just a second. I'm sorry, the line's busy. Do you want to ",
      { word: "word8" },
      "? Okay, I'll hold. Hello? Hi Barbara, it's me, Rob. Rob, hi. I tried to call you ",
      { word: "word9" },
      ". What did you want to talk about?",
    ],
  },
  {
    id: 18,
    title: "Episode 6 - Central Park Again", // Título do vídeo
    videoSrc: "https://www.youtube.com/embed/JsznSy190yQ",
    words: [
      { id: "word1", correctAnswer: "thought" },
      { id: "word2", correctAnswer: "offered" },
      { id: "word3", correctAnswer: "pleased" },
      { id: "word4", correctAnswer: "sent" },
      { id: "word5", correctAnswer: "quitting" },
      { id: "word6", correctAnswer: "hasn't" },
      { id: "word7", correctAnswer: "read" },
      { id: "word8", correctAnswer: "opened" },
      { id: "word9", correctAnswer: "explain" },
    ],
    videoDescription: [
      "Jenny! Rob, I have something to tell you. I have something to tell you too. You go first. Well, I ",
      { word: "word1" },
      "again about moving to London. But you don't need to move to London. What? Barbara called me earlier. What about? She ",
      { word: "word2" },
      "me a job. Here, in New York. What? Oh, that's great news. You don't seem very ",
      { word: "word3" },
      ". I am. I mean, it's great. It's just that... What? I",
      { word: "word4" },
      "Barbara an email this morning. And? I told her I was",
      { word: "word5" },
      "and moving to London. Don't worry. Maybe she",
      { word: "word6" },
      "read your email yet. I'll call her. Hello, Barbara Keaton. Barbara, it's Jenny. Oh, hi Jenny. Um, have you",
      { word: "word7" },
      "your emails recently? There's one from me. Oh, yes. I can see it. I haven't",
      { word: "word8" },
      "it yet. Don't open it. Delete it. Please, just delete it. I'll",
      { word: "word9" },
      "later. Okay. It's gone. Is everything alright, Jenny? Yes, thanks. Never better.",
    ],
  },
];

// Componente genérico para cada vídeo
const VideoWithDescription = ({ title, videoSrc, words, videoDescription }) => {
  // Estado para controlar os inputs
  const [inputs, setInputs] = useState(
    videoDescription
      .filter((item) => item.word) // Só consideramos as palavras
      .map((item) => ({
        id: item.word,
        value: "",
        correctAnswer: words.find((w) => w.id === item.word).correctAnswer,
      }))
  );

  // Estado para controlar a visibilidade da descrição
  const [isDescriptionVisible, setIsDescriptionVisible] = useState(false);

  // Função para alternar a visibilidade da descrição
  const toggleDescription = () => {
    setIsDescriptionVisible((prevState) => !prevState);
  };

  // Função para verificar se o input está correto
  const handleInputChange = (e, id) => {
    const { value } = e.target;
    setInputs((prevInputs) =>
      prevInputs.map((input) =>
        input.id === id
          ? {
              ...input,
              value,
            }
          : input
      )
    );
  };

  return (
    <div className="container-main">
      <p className="title-video">{title}</p> {/* Exibindo o título do vídeo */}
      <div className="video-container">
        <iframe
          src={videoSrc}
          title="Video"
          frameBorder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
          className=""
        ></iframe>
      </div>
      <div className="text-center">
        <button className="button-video" onClick={toggleDescription}>
          {" "}
          <FaChevronCircleDown className="video-icon" />
        </button>
      </div>
      {isDescriptionVisible && (
        <p className="video-description">
          {videoDescription.map((item, index) => {
            if (item.word) {
              // Encontrar o input correspondente
              const input = inputs.find((i) => i.id === item.word);
              return (
                <input
                  key={index}
                  type="text"
                  value={input?.value}
                  onChange={(e) => handleInputChange(e, item.word)} // Usando onChange para validação enquanto digita
                  style={{
                    margin: "0 5px",
                    padding: "12px 0",
                    width: "35vw",
                    textAlign: "center",
                    fontSize: "14px",
                    border: "1px solid gray",
                    borderRadius: "5px",
                    borderColor:
                      input?.value.toLowerCase() ===
                      input?.correctAnswer.toLowerCase()
                        ? "green"
                        : "rgb(201, 99, 99)",
                    backgroundColor:
                      input?.value.toLowerCase() ===
                      input?.correctAnswer.toLowerCase()
                        ? "green"
                        : "rgb(201, 99, 99)",
                    color:
                      input?.value.toLowerCase() ===
                      input?.correctAnswer.toLowerCase()
                        ? "white"
                        : "black",
                    outline: "none",
                  }}
                />
              );
            } else {
              return <span key={index}>{item}</span>;
            }
          })}
        </p>
      )}
      <hr className="line-video" />
    </div>
  );
};

// Componente principal que renderiza todos os vídeos
const PraticalEnglish2 = () => {
  return (
    <div>
      <OptionsTop></OptionsTop>
      {VideoData.map((video) => (
        <VideoWithDescription
          key={video.id}
          title={video.title} // Passando o título como prop
          videoSrc={video.videoSrc}
          words={video.words}
          videoDescription={video.videoDescription}
        />
      ))}
    </div>
  );
};

export default PraticalEnglish2;
